[fun] Disable per-line background color, because it doesn't look good for Valsary.fun.
The other files I have have black background anyway.
Exception: Girls.vic has one pink background line, but there are no background pixels in this line.